version: "3"
services:
  hydra-backend:
    build:
          context: ../services/BackedForFrontend
          dockerfile: Dockerfile
    container_name: hydra-backend
    expose:
      - "4060"
    ports:
      - "4060:4060"
    #depends_on:
    networks:
      - tmdbhydra-network

  web-interface-react:
    build:
          context: ../services/WebInterfaceReact
          dockerfile: Dockerfile
    container_name: web-interface-react
    command: react-scripts start
    stdin_open: true
    tty: true
    expose:
      - "3001"
    ports:
      - "3001:3001"
    #depends_on:
    networks:
      - tmdbhydra-network

networks:
  tmdbhydra-network:
    driver: bridge
